### ISSUE TITLE
Are datasets size expanded with prompts number?

### ISSUE THREAD

**Issue by wangpuyi** [khawar-islam/diffuseMix#6]
Thank you for the impressive work you have done. During my use, I encountered a question that I hope to get your help with.

I am curious whether the size of the dataset used for training increases linearly with the number of prompts? To put it simply, is the datasets expanded by 10 times if the number of prompts is 10? I couldn't find related information in the documentation.

Looking forward to your response, and once again, thank you for your exceptional contributions to this project!

**Comment by khawar-islam** [comment]
Dear @wangpuyi 

Thanks for your message. Yes, yes the dataset expanded by 10 times but you can just set 2 prompts and train the model so that it can save you time and you can get better performance no need to set whole 10 prompts because if you GPU is not good then it takes long time to generate the images.

If you have any question, please let me know

**Comment by wangpuyi** [comment]
Dear @khawar-islam 

Thank you for your fast reply.

I am sorry to say this, but it seems unfair if you have expanded the dataset by tenfold, while other methods have not increased the number of training images (such as CutMix) or have not significantly increased the dataset size (like GuidedMixup).

From Figure 5 in your method, it is evident that the training results are highly influenced by the number of images in the dataset. When the dataset is increased tenfold, there is an improvement of over 10 points on the CUB dataset. Moreover, since the network is trained from scratch, the volume of data used for training might be more pronounced.

Following are some concrete questions:
1.Have you conducted comparisons using the same amount of dataset? Could  you please show some results with me?
2.Will the increment be subtle if the network(e.g. resnet50) are pretrained rather than training from scratch?
3.On Figure 6, you show the result with dataset enlarged by tenfold. It meant to be 1,000% augmentation overhead in this case, isn't it?
4.Could you share the parameters used to train your network?

 I appreciate your opinion on this. Thanks for your time.

**Comment by khawar-islam** [comment]
Dear @wangpuyi 

Apologies for the delayed response and thanks for these interesting questions. While it is understandable that _more_ training data could result in better performance, it is not always the case and there are a few things that should be clarified: 

1) First of all, it is important to note that all augmentation methods generate new data which they refer to as augmented images. In DiffuseMix, like other augmentation methods, the base dataset remains the same while augmented images are generated using the diffusion model. Therefore, comparison with other augmentation methods remains fair because the baseline dataset is the same, while augmentations are different.

2) In DiffuseMix, we generate nine augmented images for each training input image. If there are 8000 images in the training dataset, diffusemix will generate 72k images for offline training. Compared to that, in other mixing-based methods, in each epoch, the number of augmented images is usually equal to the number of training images. If there are, for example, 200 epochs and 8000 images in the dataset, mixing-based methods will generate 1600k augmented images. Thus the number of augmented images generated by these methods is significantly larger than DiffuseMix.

In the light of this, the answers to your questions are below: 

1) The base training data remains the same across all compared algorithms. However, the number of augmentations varies from method to method. Reducing the number of augmentations in compared methods to 9 times the dataset size (72k for the example given above) may have adverse effects on their performance.

2) We have experimented on pre-training as well as training from scratch and the results are reported in the paper.

3) In Figure 6, augmentation overhead is shown which relates to the cost of augmentation and not the folds increase in the dataset. Some methods take more computational cost to compute 1 augmentation while others are fast. Moreover, during training, some methods converge earlier on lesser epochs while others take more epochs to converge. This figure shows the relative cost of augmentation and training across different algorithms.

4) Please refer to our GitHub page for implementation details https://github.com/khawar-islam/Stanford-Cars and let me know if you require any further specific information.

**Comment by wangpuyi** [comment]
@khawar-islam 
Thanks you very much. I learned a lot from your insightful and kind reply.
